export const HostLabels = {
  GLOBAL: 'Global',
  EDGE: 'Edge',
  ORIGIN: 'Origin',
  DOMAIN: 'Domain',
};

export const endPointHostGrouping = {
  [HostLabels.EDGE]: [
    'fetchSection',
    'fetchSectionSections',
    'seriesSeasonEpisodes',
    'contentProducts',
    'products',
  ],
  [HostLabels.ORIGIN]: [],
  [HostLabels.GLOBAL]: [
    'contentComments',
    'postContentComment',
    'deleteComment',
    'reportComment',
    'getRepliesToComment',
    'getRepliesAfterReplyToComment',
    'getRepliesInbetweenTwoRepliesToComment',
    'postReplyToComment',
    'likeAComment',
    'fetchPlatformId',
    'memberInvite',
    'memberRegistration',
    'purchase',
    'memberAuth',
    'memberOutbound',
    'memberTokenRefresh',
    'memberProfile',
    'fetchMemberEnablement',
    'fetchMemberContent',
    'memberUpload',
    'memberPayment',
    'addMemberPayment',
    'contentLike',
    'contentView',
    'contentBookmark',
    'notificationPrefs',
    'addNotificationPref',
    'rmNotificationPref',
    'memberFollowing',
    'followStar',
    'unfollowStar',
    'cancelMembership',
    'paymentHistory',
    'zendeskToken',
    'notificationDeviceRegister',
    'tracking',
    'showReel',
    'fetchACommentByContentIdAndCommentId',
  ],
  [HostLabels.DOMAIN]: [
    'fetchTemplateSections',
    'fetchSectionItems',
    'fetchContentItem',
    'fetchContentEntitlement',
    'fetchRelatedContentSection',
    'fetchStars',
    'search',
    'gallery',
    'fetchStar',
    'bookmarks',
  ],
};

export const endPoints = {
  //Content & Platform
  fetchContentItem: ({ id }) => `/content/${id}`,
  fetchSection: ({ sectionId }) => `/merchandise/section/${sectionId}`,
  fetchSectionItems: ({ sectionId }) => `/section/items/${sectionId}`,
  fetchSectionSections: ({ sectionId }) => `/merchandise/section/${sectionId}/section`,
  fetchPlatformId: () => '/merchandise/platform',
  fetchContentEntitlement: ({ contentId }) => `/enablement/content/${contentId}/entitlement`,
  fetchMemberEnablement: () => '/enablement/status',
  fetchTemplateSections: ({ templateId }) => `/template/section/${templateId}`,
  fetchRelatedContentSection: ({ contentId }) => `/content/${contentId}/related`,
  contentLike: ({ contentId }) => `/social/content/${contentId}/like`,
  contentView: ({ contentId }) => `/social/content/${contentId}/view`,
  contentBookmark: ({ contentId }) => `/social/content/${contentId}/bookmark`,
  bookmarks: () => '/bookmarks',
  seriesSeasonEpisodes: ({ seriesId, seasonId }) =>
    `/inventory/series/${seriesId}/season/${seasonId}/episodes`,

  //Content Comments
  showReel: ({ contentId }) => `/comment/content/${contentId}/comments/showreel`,
  fetchACommentByContentIdAndCommentId: ({ contentId, commentId }) =>
    `/comment/content/${contentId}/comment/${commentId}/showreel`,
  contentComments: ({ contentId }) => `/comment/content/${contentId}/comment`,
  postContentComment: ({ contentId }) => `/comment/content/${contentId}/comment`,
  getRepliesToComment: ({ contentId, commentId }) =>
    `/comment/content/${contentId}/comment/${commentId}/replies`,
  getRepliesAfterReplyToComment: ({ replyId, parentId }) =>
    `/comment/${replyId}/parent/${parentId}`,
  getRepliesInbetweenTwoRepliesToComment: ({ replyId, parentId, nextImportantReplyId }) =>
    `/comment/after/${replyId}/before/${nextImportantReplyId}/parent/${parentId}`,
  postReplyToComment: ({ contentId, commentId }) =>
    `/comment/content/${contentId}/comment/${commentId}/reply`,
  deleteComment: ({ contentId, commentId }) => `/comment/content/${contentId}/comment/${commentId}`,
  reportComment: ({ contentId, commentId }) =>
    `/comment/content/${contentId}/comment/${commentId}/report`,
  likeAComment: ({ contentId, commentId }) =>
    `/comment/content/${contentId}/comment/${commentId}/like`,

  //Stars
  fetchStars: () => '/stars',
  fetchStar: ({ starId }) => `/star/${starId}`,
  followStar: ({ starId }) => `/social/star/${starId}`,
  unfollowStar: ({ starId }) => `/social/star/${starId}`,
  memberFollowing: ({ memberId }) => `/social/member/${memberId}/stars`,

  //Member & Misc
  memberUpload: () => '/member/upload/sign',
  fetchMemberContent: ({ id }) => `/social/member/${id}/content`,
  memberTokenRefresh: () => '/member/auth/token/refresh',
  memberProfile: () => '/member/profile',
  memberOutbound: () => '/member/outbound',
  memberAuth: () => '/member/auth',
  memberRegistration: () => '/member/registration',
  memberInvite: ({ memberId }) => `/member/${memberId}/invite`,
  memberPayment: ({ memberId }) => `/member/${memberId}/payment`,
  addMemberPayment: () => '/member/payment',
  gallery: ({ galleryId }) => `/gallery/${galleryId}`,
  notificationPrefs: () => '/member/notification/preferences',
  addNotificationPref: () => '/member/notification/preference',
  rmNotificationPref: ({ channel }) => `/member/notification/preferences/${channel}`,
  contentProducts: ({ contentId }) => `/commerce/content/${contentId}/product`,
  products: () => '/commerce/product',
  purchase: () => '/purchase',
  search: () => '/search/all',
  cancelMembership: ({ enablementId }) => `/purchase/enablement/${enablementId}`,
  paymentHistory: () => '/enablement/paymenthistory',
  zendeskToken: () => '/zendesk/token',
  notificationDeviceRegister: () => '/member/notification/device',
  tracking: () => '/member/tracking',
};
