export const FETCH_STRIPE_TOKEN_REQUEST = 'FETCH_STRIPE_TOKEN_REQUEST';
export const FETCH_STRIPE_TOKEN_SUCCESS = 'FETCH_STRIPE_TOKEN_SUCCESS';
export const FETCH_STRIPE_TOKEN_FAILURE = 'FETCH_STRIPE_TOKEN_FAILURE';
