export default [
  {
    time: 16000,
    externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
    postedDateTime: 1582663817143,
    comment: 'GG',
    avatarUrl:
      'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Bruno',
    surname: 'Lago',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
    postedDateTime: 1581079099376,
    comment: 'Wooow',
    nickname: 'Mohammad Banaderi',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Mohammad',
    surname: 'Banaderi',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  // {
  //   time: 16000,
  //   externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
  //   postedDateTime: 1576734479356,
  //   comment: 'Genioooollll',
  //   nickname: 'Bautista Peirano',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Bautista',
  //   surname: 'Peirano',
  //   memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
  // {
  //   time: 16000,
  //   externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
  //   postedDateTime: 1576259890052,
  //   comment: '❤️❤️❤️❤️',
  //   avatarUrl:
  //     'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
  //   nickname: 'Andrea Ceballos',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Andrea',
  //   surname: 'Ceballos',
  //   memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
  // {
  //   time: 16000,
  //   externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
  //   postedDateTime: 1576157447699,
  //   comment: 'Paulo Dybala❤️',
  //   nickname: 'Shirley Francisca Libombo',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Shirley Francisca',
  //   surname: 'Libombo',
  //   memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
];
