export default [
  {
    time: 16000,
    externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
    postedDateTime: 1582663817143,
    comment: 'The goal against de gea was insane 🐐',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJyScMTmcUX1LmIV5wv4Arpp3CN-RrMT3p3BWA=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Arry',
    surname: 'Sammy',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
    postedDateTime: 1581919062973,
    comment: 'RONALDOOOOOOOOOOOO OOOOOOOOOOOOOOOOOOOOO !!!!!!!!',
    nickname: 'Ricardo  D. ',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJwfSeCWUBxVt5HHR-iLsMrHqI67pLlpkuQyyQ=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Elvyn ',
    surname: 'Watson',
    memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
    postedDateTime: 1581079141092,
    comment: 'Thanks for coming to Juve Cristiano you are the best',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJzdbWROHFgowMCwI7v6WiJNWA4tVfyoAaXWhA=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Marco',
    surname: 'Cosentino',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
    postedDateTime: 1581079113209,
    comment: 'El gol de chilena es el unico diferente lol',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJwrhzn-A06XHrrn7QTwAuF4r-4wAKLWFprX=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Axel',
    surname: 'Gaytan',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
    postedDateTime: 1581079099376,
    comment:
      "Even I am a Juventus fan for several years I have to say that Ronaldo's overhead goal at Juventus Stadium " +
      "was absolutely fantastic.I didn't have any words to describe how incredible it was to look at that beauty. " +
      'In my opinion, this goal really deserved applause from Juventus fans. This is another proof why Ronaldo is ' +
      'supposed to be one of the greatest footballers in the football history. I consider him to be an outstanding phenomenon. ' +
      'That is why I actually feel completely happy admiring the enormous number of goals scored by Cristiano and ' +
      'all the spectacular skills that he demonstrates to his supporters',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJzbJpn1DoWb1kNBopzntHGYPHzHHN97nc8qRg=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Haris',
    surname: 'Mehmood',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
    postedDateTime: 1582663817143,
    comment: '🐐🐐🐐🐐 All this and then you gave Luka the Best player , is this a joke ??',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJyScMTmcUX1LmIV5wv4Arpp3CN-RrMT3p3BWA=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Arry',
    surname: 'Sammy',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 16000,
    externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
    postedDateTime: 1581919062973,
    comment: 'Ronaldo is so far away from Messi it’s unbelievable',
    nickname: 'Ricardo  D. ',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJwfSeCWUBxVt5HHR-iLsMrHqI67pLlpkuQyyQ=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Elvyn ',
    surname: 'Watson',
    memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
];
