export default [
  {
    time: 6000,
    externalId: '9bf52549123-92e5-4c80-8a57-6b4c7a7fb1b5',
    postedDateTime: 1581079141092,
    comment: 'Thanks for coming to Juve Cristiano you are the best',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJzdbWROHFgowMCwI7v6WiJNWA4tVfyoAaXWhA=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Marco',
    surname: 'Cosentino',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 6000,
    externalId: '25796eed-46de-4356-sdf9212-d850bd9bcb0b',
    postedDateTime: 1581079113209,
    comment: 'El gol de chilena es el unico diferente lol',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJwrhzn-A06XHrrn7QTwAuF4r-4wAKLWFprX=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Axel',
    surname: 'Gaytan',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
];
