export default [
  {
    time: 5000,
    externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
    postedDateTime: 1582663817143,
    comment: 'The King!',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJzvQwYqwqyr59gacbu-MNiJwu9sxRkf3YsndQ=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Gabie',
    surname: 'Stone',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 5000,
    externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
    postedDateTime: 1581079099376,
    comment: 'HE IS INCREDIBLE :)',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJz1OHy7ZaDpYx8iO_RWavFwi7v3vnLx0XOyrw=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Rupkahta Bhowmik',
    surname: 'Banaderi',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  // {
  //   time: 5000,
  //   externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
  //   postedDateTime: 1576734479356,
  //   comment: 'King of football 💪🔥',
  //   nickname: 'Bautista Peirano',
  //   avatarUrl:
  //     'https://yt3.ggpht.com/a/AATXAJzg88jviHZqGEuUS-67L1LiohfW3uM-j5ymCQ=s48-c-k-c0xffffffff-no-rj-mo',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Tra',
  //   surname: 'Roddy',
  //   memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
  // {
  //   time: 5000,
  //   externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
  //   postedDateTime: 1576157447699,
  //   comment: 'Everything was so perfect and I still want him to play for real Madrid :(',
  //   nickname: 'Shirley Francisca Libombo',
  //   avatarUrl:
  //     'https://yt3.ggpht.com/a/AATXAJyZDPJy5fpx9VV3yo24Syn4-SA1W5BoWMsKWw=s48-c-k-c0xffffffff-no-rj-mo',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Shirley Francisca',
  //   surname: 'Libombo',
  //   memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
  // {
  //   time: 5000,
  //   externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec5',
  //   postedDateTime: 1581079099376,
  //   comment: 'No one even come close to the legend !',
  //   nickname: 'Mohammad Banaderi',
  //   avatarUrl:
  //     'https://yt3.ggpht.com/a/AATXAJz1OHy7ZaDpYx8iO_RWavFwi7v3vnLx0XOyrw=s48-c-k-c0xffffffff-no-rj-mo',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Rupkahta Bhowmik',
  //   surname: 'Banaderi',
  //   memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
  // {
  //   time: 5000,
  //   externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
  //   postedDateTime: 1576734479356,
  //   comment: 'The Legend ! Greated of all times ! Messi WHO ? :D  💪🔥',
  //   nickname: 'Bautista Peirano',
  //   avatarUrl:
  //     'https://yt3.ggpht.com/a/AATXAJzg88jviHZqGEuUS-67L1LiohfW3uM-j5ymCQ=s48-c-k-c0xffffffff-no-rj-mo',
  //   star: false,
  //   vip: false,
  //   expandable: false,
  //   numberOfReplies: 0,
  //   numberOfLikes: 0,
  //   userReplies: [],
  //   importantReplies: [],
  //   reported: false,
  //   reportCleared: false,
  //   owner: false,
  //   likedByMe: false,
  //   forename: 'Tra',
  //   surname: 'Roddy',
  //   memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
  //   removed: false,
  //   blocked: false,
  //   hidden: false,
  //   expandAfter: false,
  //   reply: false,
  // },
];
