export default [
  {
    time: 11000,
    externalId: 'c79ea7de-94b6-4603-b60a-6e737949658b31',
    postedDateTime: 1582663817143,
    comment: 'Y CON USTEDES PENALDO, SIIIIIIUUUU JAJAJAJAJAJAJAJA RIDICULO.',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJx1PvBbE-DaKhxFP2hOsQ0KbYPIgXSLJaJ2sQ=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Roman',
    surname: 'Reigns',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 11000,
    externalId: 'c79ea7de-94c6-46a3-b60a-6e737949128b31',
    postedDateTime: 1582663817143,
    comment: 'Its Ronaldo League ;) ',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJziMBKKm6vXY7-jKIPAFHJdOaLphibv8qDLDA=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Roman',
    surname: 'Reigns',
    memberId: '81a05ba1-ca2a-4bb9-b378-2543e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 11000,
    externalId: 'c79ea7de-94b6-4612303-b60a-6e7379498b31',
    postedDateTime: 1582663817143,
    comment: "Its not Ronaldo League. Its Ronaldo's Game ! ;)",
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJx1PvBbE-DaKhxFP2hOsQ0KbYPIgXSLJaJ2sQ=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Roman',
    surname: 'Reigns',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 11000,
    externalId: 'c79ea7de-94c6-4ga3-c60a-6e737679498b31',
    postedDateTime: 1582663817143,
    comment: "Of course it is and he if the eff'in GOAT !  👑👍❤🏆⚽ JUVE ⚽🏆❤👍👑 King 👑👍❤🏆⚽",
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJziMBKKm6vXY7-jKIPAFHJdOaLphibv8qDLDA=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Roman',
    surname: 'Reigns',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
];
