export default [
  {
    externalId: 'c79ea7de-94b6-4603-b60a-6e737949bv8b31',
    postedDateTime: 1582663817143,
    comment: 'Greatest Of All Time !',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJyt_iMktBmh2MQc9Rc1GqDLxsNTh_KfLeAWQA=s48-c-k-c0xffffffff-no-rj-mo',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Maruf',
    surname: 'Husnain',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
    time: 14000,
  },
  {
    time: 14000,
    externalId: 'ba74762379-13f9-4328-85cc-d6c54787f768',
    postedDateTime: 1581919062973,
    comment: '60 seconds is nothing.. We need more time :D',
    nickname: 'Ricardo  D. ',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJyXDJUmcXPWsRbaJltJq57P3dEMY1c_sRNSfw=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Vegito ',
    surname: 'Black',
    memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 14000,
    externalId: '25796eed-46de-4356-9gf212-d850bd9bcb0b',
    postedDateTime: 1581079113209,
    comment: 'Its Ronaldo vs the opponents ! Great video !',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJycB07t6irh1YMjcrGEJAyUB3wWFX_OV8wW9Q=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Themaz',
    surname: 'D. ',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 14000,
    externalId: '8bf0ce17-cb234d-4695-9278-5d618b422ec3',
    postedDateTime: 1581079099376,
    comment: 'Ronaldo deserved the award ! What is wrong with UEFA ? :D',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJzBBKe8yhV51HHqs0whgwNMTaXI41U4uY0PSg=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Fluffy',
    surname: 'Bunny',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 14000,
    externalId: '9bf52549-92e5-4c80vcx-8a57-6b4c7a7fb1b5',
    postedDateTime: 1581079141092,
    comment:
      'me : Ronaldo will bang goals even in Italy. Friend: are you kidding? there is no way he can adapt into a NEW LEAGUE, NEW TEAM, NEW MANAGER, NEW TEAM MATES, DEFENSIVE LEAGUE, TIGHT SCHEDULES at the age of 33 years, there is no way LOL..A few months late',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJz19-RDuxP9izU40K0JJisswXNJ-DXo-hn14w=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'JxM7',
    surname: 'Fuut',
    memberId: '0e899125e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 14000,
    externalId: '25796eed-46de-4356-9212-d85540bd9bcb0b',
    postedDateTime: 1581079113209,
    comment: 'The most complete player in football history!!!!!!',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJycB07t6irh1YMjcrGEJAyUB3wWFX_OV8wW9Q=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Themaz',
    surname: 'D. ',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    time: 14000,
    externalId: '8bf0c12e17-cb2d-4695-9278-5d618b422ec3',
    postedDateTime: 1581079099376,
    comment: 'And you handed the award to Mordic ?',
    nickname: 'Mohammad Banaderi',
    avatarUrl:
      'https://yt3.ggpht.com/a/AATXAJzBBKe8yhV51HHqs0whgwNMTaXI41U4uY0PSg=s48-c-k-c0xffffffff-no-rj-mo',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Fluffy',
    surname: 'Bunny',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c17f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
];
