export default [
  {
    externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
    postedDateTime: 1582663817143,
    comment: 'GG',
    avatarUrl:
      'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
    nickname: 'Bruno Lago',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Bruno',
    surname: 'Lago',
    memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
    postedDateTime: 1581919062973,
    comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
    nickname: 'Ricardo  D. ',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Ricardo ',
    surname: 'D. ',
    memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
    postedDateTime: 1581079141092,
    comment: 'Life ❤',
    nickname: 'Mohammad Banaderi',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Mohammad',
    surname: 'Banaderi',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
    postedDateTime: 1581079113209,
    comment: 'Best  player ',
    nickname: 'Mohammad Banaderi',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Mohammad',
    surname: 'Banaderi',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
  {
    externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
    postedDateTime: 1581079099376,
    comment: 'Wooow',
    nickname: 'Mohammad Banaderi',
    star: false,
    vip: false,
    expandable: false,
    numberOfReplies: 0,
    numberOfLikes: 0,
    userReplies: [],
    importantReplies: [],
    reported: false,
    reportCleared: false,
    owner: false,
    likedByMe: false,
    forename: 'Mohammad',
    surname: 'Banaderi',
    memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
    removed: false,
    blocked: false,
    hidden: false,
    expandAfter: false,
    reply: false,
  },
];
