const FETCH_PAYMENT_METHODS_REQUEST = 'FETCH_PAYMENT_METHODS_REQUEST';
const FETCH_PAYMENT_METHODS_SUCCESS = 'FETCH_PAYMENT_METHODS_SUCCESS';
const FETCH_PAYMENT_METHODS_FAILURE = 'FETCH_PAYMENT_METHODS_FAILURE';
const ADD_PAYMENT_METHOD_REQUEST = 'ADD_PAYMENT_METHODS_REQUEST';
const ADD_PAYMENT_METHOD_SUCCESS = 'ADD_PAYMENT_METHODS_SUCCESS';
const ADD_PAYMENT_METHOD_FAILURE = 'ADD_PAYMENT_METHODS_FAILURE';

export {
  FETCH_PAYMENT_METHODS_REQUEST,
  FETCH_PAYMENT_METHODS_SUCCESS,
  FETCH_PAYMENT_METHODS_FAILURE,
  ADD_PAYMENT_METHOD_REQUEST,
  ADD_PAYMENT_METHOD_SUCCESS,
  ADD_PAYMENT_METHOD_FAILURE,
};
