import React from 'react';
import { connect } from 'react-redux';
import { compose, includes } from 'lodash/fp';
import { FormattedMessage } from 'react-intl';
import withRequest from 'xi-core/withRequest';
import { isLoading, REPLIES_LOAD_TYPE } from 'xi-core/comments/selectors';
import styled from 'styled-components';
import navPresenter from 'xi-core/navigation/NavigationPresenter';
import { Grey85 } from 'xi-core/colours';
import { commentsPageInteraction } from 'xi-core/comments/actions';
import { PropertyKeys } from 'xi-core/analytics/analyticEvents';
import LoaderSpinner from '../common/LoaderSpinner';
import Comment, { RepliesInfo, RepliesInfoContainer } from './Comment';

const Container = styled.div`
  position: relative;
  color: ${Grey85};
  background: white;
  padding-top: 20px;
  ${props => (props.isTopLevel ? '' : 'padding-top: 0px')}
`;

const Wrapper = styled.div`
  display: ${({ hidden }) => (hidden ? 'none' : 'block')};
`;

const StyledLoaderSpinner = styled(LoaderSpinner)`
  width: 100%;
  text-align: center;
  margin: 10px 0px;
`;

class CommentBlock extends React.Component {
  state = {
    hidden: false,
  };

  componentDidUpdate = prevProps => {
    const { isAnotherPage, contentId, hasReachedEnd } = this.props;
    navPresenter.setCurrentContent(contentId);

    // if (hasReachedEnd && !prevProps.hasReachedEnd && isAnotherPage()) {
    //   this.props.getNextPage();
    // }
    if (hasReachedEnd && !prevProps.hasReachedEnd) {
      console.log('End reached');
      // this.props.getNextPage();
    }
  };

  hasMorePagesOfReplies = requestType => {
    const { isLoading, loadType, isAnotherPage } = this.props;
    return !isLoading && loadType === requestType && isAnotherPage();
  };

  handleRenderHideRepliesCtaClick = (e, loadType) => {
    e.preventDefault();
    this.setState({ hidden: true });

    const { pageInteraction } = this.props;
    let eventName = '';

    switch (loadType) {
      case REPLIES_LOAD_TYPE.PREVIOUS_REPLIES:
        eventName = PropertyKeys.COMMENTS_PAGE.HIDE_PREVIOUS_REPLIES_CLICKED;
        break;
      case REPLIES_LOAD_TYPE.MORE_REPLIES:
      case REPLIES_LOAD_TYPE.ALL_REPLIES:
        eventName = PropertyKeys.COMMENTS_PAGE.HIDE_REPLIES_CLICKED;
        break;
      default:
        break;
    }

    pageInteraction(eventName);
  };

  renderHideRepliesCta = loadType => {
    const { isTopLevelComment } = this.props;

    let dataTestId = 'hide-replies';
    if (loadType === REPLIES_LOAD_TYPE.PREVIOUS_REPLIES) {
      dataTestId = 'hide-previous-replies';
    }

    return (
      <RepliesInfoContainer isTopLevelComment={isTopLevelComment}>
        <RepliesInfo
          data-test-id={dataTestId}
          onClick={e => this.handleRenderHideRepliesCtaClick(e, loadType)}
        >
          {'- - - - - - - '}
          {loadType === REPLIES_LOAD_TYPE.PREVIOUS_REPLIES && (
            <FormattedMessage
              id="comments.hide_previous_replies"
              defaultMessage="Hide previous replies"
            />
          )}
          {includes(loadType, [REPLIES_LOAD_TYPE.ALL_REPLIES, REPLIES_LOAD_TYPE.MORE_REPLIES]) && (
            <FormattedMessage id="comments.hide_replies" defaultMessage="Hide replies" />
          )}
        </RepliesInfo>
      </RepliesInfoContainer>
    );
  };

  handleRenderViewRepliesCtaClick = (e, loadType, withGetNextPageRequest) => {
    e.preventDefault();
    const { pageInteraction, getNextPage } = this.props;
    withGetNextPageRequest ? getNextPage() : this.setState({ hidden: false });

    let eventName = '';

    switch (loadType) {
      case REPLIES_LOAD_TYPE.PREVIOUS_REPLIES:
        eventName = PropertyKeys.COMMENTS_PAGE.VIEW_PREVIOUS_REPLIES_CLICKED;
        break;
      case REPLIES_LOAD_TYPE.MORE_REPLIES:
        eventName = PropertyKeys.COMMENTS_PAGE.VIEW_MORE_REPLIES_CLICKED;
        break;
      case REPLIES_LOAD_TYPE.ALL_REPLIES:
        eventName = withGetNextPageRequest
          ? PropertyKeys.COMMENTS_PAGE.VIEW_PREVIOUS_REPLIES_CLICKED
          : PropertyKeys.COMMENTS_PAGE.VIEW_REPLIES_CLICKED;
        break;
      default:
        break;
    }

    eventName && pageInteraction(eventName);
  };

  renderViewRepliesCta = ({ loadType, withGetNextPageRequest = false }) => {
    const { isTopLevelComment } = this.props;

    let dataTestId = '';
    if (loadType === REPLIES_LOAD_TYPE.ALL_REPLIES) {
      dataTestId = 'view-all-replies';
    } else if (loadType === REPLIES_LOAD_TYPE.MORE_REPLIES) {
      dataTestId = 'view-more-replies';
    } else if (loadType === REPLIES_LOAD_TYPE.PREVIOUS_REPLIES) {
      dataTestId = 'view-previous-replies';
    }

    return (
      <RepliesInfoContainer isTopLevelComment={isTopLevelComment}>
        <RepliesInfo
          data-test-id={dataTestId}
          onClick={e => this.handleRenderViewRepliesCtaClick(e, loadType, withGetNextPageRequest)}
        >
          {'- - - - - - - '}
          {loadType === REPLIES_LOAD_TYPE.ALL_REPLIES && withGetNextPageRequest && (
            <FormattedMessage
              id="comments.view_previous_replies"
              defaultMessage="View previous replies"
            />
          )}
          {loadType === REPLIES_LOAD_TYPE.ALL_REPLIES && !withGetNextPageRequest && (
            <FormattedMessage id="comments.view_all_replies" defaultMessage="View all replies" />
          )}
          {loadType === REPLIES_LOAD_TYPE.PREVIOUS_REPLIES && (
            <FormattedMessage
              id="comments.view_previous_replies"
              defaultMessage="View previous replies"
            />
          )}
          {loadType === REPLIES_LOAD_TYPE.MORE_REPLIES && (
            <FormattedMessage id="comments.view_more_replies" defaultMessage="View more replies" />
          )}
        </RepliesInfo>
      </RepliesInfoContainer>
    );
  };

  render = () => {
    const {
      comments,
      contentId,
      focusTextArea,
      isLoading,
      parentId,
      loadType,
      replyId,
    } = this.props;

    const { hidden } = this.state;

    return (
      <Container isTopLevel={!parentId ? true : false}>
        {includes(loadType, [REPLIES_LOAD_TYPE.ALL_REPLIES, REPLIES_LOAD_TYPE.PREVIOUS_REPLIES]) ? (
          isLoading ? (
            <StyledLoaderSpinner />
          ) : this.hasMorePagesOfReplies(loadType) ? (
            this.renderViewRepliesCta({ loadType: loadType, withGetNextPageRequest: true })
          ) : !hidden ? (
            this.renderHideRepliesCta(loadType)
          ) : (
            this.renderViewRepliesCta({ loadType: loadType, withGetNextPageRequest: false })
          )
        ) : null}

        <Wrapper hidden={hidden}>
          {comments.map(comment => {
            return comment.externalId !== replyId ? (
              <Comment
                key={comment.externalId}
                comment={comment}
                contentId={contentId}
                focusTextArea={focusTextArea}
              />
            ) : null;
          })}
        </Wrapper>

        {isLoading && !parentId && <StyledLoaderSpinner />}

        {loadType === REPLIES_LOAD_TYPE.MORE_REPLIES ? (
          isLoading ? (
            <StyledLoaderSpinner />
          ) : this.hasMorePagesOfReplies(loadType) ? (
            this.renderViewRepliesCta({ loadType: loadType, withGetNextPageRequest: true })
          ) : !hidden ? (
            this.renderHideRepliesCta(loadType)
          ) : (
            this.renderViewRepliesCta({ loadType: loadType, withGetNextPageRequest: false })
          )
        ) : null}
      </Container>
    );
  };
}

const mapStateToProps = (state, { contentId, parentId, loadType, replyId }) => {
  return {
    isLoading: isLoading(state)(contentId, parentId, loadType ? loadType + ',' + replyId : null),
    comments: [
      {
        externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
        postedDateTime: 1582663817143,
        comment: 'GG',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
        nickname: 'Bruno Lago',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bruno',
        surname: 'Lago',
        memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
        postedDateTime: 1581919062973,
        comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
        nickname: 'Ricardo  D. ',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Ricardo ',
        surname: 'D. ',
        memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
        postedDateTime: 1581079141092,
        comment: 'Life ❤',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
        postedDateTime: 1581079113209,
        comment: 'Best  player ',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
        postedDateTime: 1581079099376,
        comment: 'Wooow',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
        postedDateTime: 1576734479356,
        comment: 'Genioooollll',
        nickname: 'Bautista Peirano',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bautista',
        surname: 'Peirano',
        memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
        postedDateTime: 1576259890052,
        comment: '❤️❤️❤️❤️',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
        nickname: 'Andrea Ceballos',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Andrea',
        surname: 'Ceballos',
        memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
        postedDateTime: 1576157447699,
        comment: 'Paulo Dybala❤️',
        nickname: 'Shirley Francisca Libombo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Shirley Francisca',
        surname: 'Libombo',
        memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9a1f4b81-37f7-4085-96ab-96d49e698b27',
        postedDateTime: 1574312808356,
        comment: '\uD83D\uDC99',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1574799206/avatar_dde77c00-a3d7-4570-b65d-7eefcf6c0c3a.jpg?type=square&width=400',
        nickname: 'Isabel Jakob',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Isabel',
        surname: 'Jakob',
        memberId: 'dde77c00-a3d7-4570-b65d-7eefcf6c0c3a',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb0cc2e2-e7f4-4e22-b1eb-6d99cc5e77aa',
        postedDateTime: 1573333064364,
        comment: 'Wowwww Pauloooo...\uD83D\uDE0D',
        avatarUrl: 'https://graph.facebook.com/10221096707835667/picture',
        nickname: 'Astryd Colella',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Astryd',
        surname: 'Colella',
        memberId: '61ae0de4-94ea-4ad7-a6a4-75c668b04a53',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb74b6f1-7da5-44e4-88bd-67e55539ffe8',
        postedDateTime: 1573322097311,
        comment: 'A',
        avatarUrl: 'https://graph.facebook.com/2171749249821485/picture',
        nickname: 'Tejas Ganesh',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Tejas',
        surname: 'Ganesh',
        memberId: '77a266c7-810f-4268-a122-aede1b04ace7',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cf75ca2d-d3f4-4d2e-8d8b-07008d093e82',
        postedDateTime: 1572965949144,
        comment: "He's a cracker.mans got an arsenal kit... respect",
        nickname: 'Sean Keenan',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Sean',
        surname: 'Keenan',
        memberId: '60d22eff-c820-4d63-9fbd-944bc76f6e22',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4577bbcd-e030-46b8-869d-ce08e8c4677f',
        postedDateTime: 1570917932084,
        comment: 'Eres el mejor Dybala●',
        nickname: 'Alejandro Hirales',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Alejandro',
        surname: 'Hirales',
        memberId: '28c1aef9-858c-4f2c-9fde-11727d998206',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '90eaa3c2-389c-4ad7-a9a5-e0aa0ab78719',
        postedDateTime: 1570237621468,
        comment: "I am your fan, I would like to meet u some day... But I'm in Brazil now.\n",
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1570236355/avatar_070da272-9353-4d98-a13c-90b8231144bf.jpg',
        nickname: 'Vinícius Melo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Vinícius',
        surname: 'Melo',
        memberId: '070da272-9353-4d98-a13c-90b8231144bf',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'b748cfca-7b6f-4eb4-bbbb-50557eb26484',
        postedDateTime: 1570067098407,
        comment:
          'Le pedi una tuya a Anto en su momento, ya que nunca se pudo dar y ahora esta esta publicación . Te puedo hacer el mangazo? :) Un abrazo.',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1555704527/avatar_be8bb93c-6a44-45e9-b61b-92251744d809.jpg?type=square&width=400',
        nickname: 'German Laso',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'German',
        surname: 'Laso',
        memberId: 'be8bb93c-6a44-45e9-b61b-92251744d809',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
        postedDateTime: 1582663817143,
        comment: 'GG',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
        nickname: 'Bruno Lago',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bruno',
        surname: 'Lago',
        memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
        postedDateTime: 1581919062973,
        comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
        nickname: 'Ricardo  D. ',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Ricardo ',
        surname: 'D. ',
        memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
        postedDateTime: 1581079141092,
        comment: 'Life ❤',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
        postedDateTime: 1581079113209,
        comment: 'Best  player ',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
        postedDateTime: 1581079099376,
        comment: 'Wooow',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
        postedDateTime: 1576734479356,
        comment: 'Genioooollll',
        nickname: 'Bautista Peirano',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bautista',
        surname: 'Peirano',
        memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
        postedDateTime: 1576259890052,
        comment: '❤️❤️❤️❤️',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
        nickname: 'Andrea Ceballos',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Andrea',
        surname: 'Ceballos',
        memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
        postedDateTime: 1576157447699,
        comment: 'Paulo Dybala❤️',
        nickname: 'Shirley Francisca Libombo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Shirley Francisca',
        surname: 'Libombo',
        memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9a1f4b81-37f7-4085-96ab-96d49e698b27',
        postedDateTime: 1574312808356,
        comment: '\uD83D\uDC99',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1574799206/avatar_dde77c00-a3d7-4570-b65d-7eefcf6c0c3a.jpg?type=square&width=400',
        nickname: 'Isabel Jakob',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Isabel',
        surname: 'Jakob',
        memberId: 'dde77c00-a3d7-4570-b65d-7eefcf6c0c3a',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb0cc2e2-e7f4-4e22-b1eb-6d99cc5e77aa',
        postedDateTime: 1573333064364,
        comment: 'Wowwww Pauloooo...\uD83D\uDE0D',
        avatarUrl: 'https://graph.facebook.com/10221096707835667/picture',
        nickname: 'Astryd Colella',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Astryd',
        surname: 'Colella',
        memberId: '61ae0de4-94ea-4ad7-a6a4-75c668b04a53',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb74b6f1-7da5-44e4-88bd-67e55539ffe8',
        postedDateTime: 1573322097311,
        comment: 'A',
        avatarUrl: 'https://graph.facebook.com/2171749249821485/picture',
        nickname: 'Tejas Ganesh',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Tejas',
        surname: 'Ganesh',
        memberId: '77a266c7-810f-4268-a122-aede1b04ace7',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cf75ca2d-d3f4-4d2e-8d8b-07008d093e82',
        postedDateTime: 1572965949144,
        comment: "He's a cracker.mans got an arsenal kit... respect",
        nickname: 'Sean Keenan',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Sean',
        surname: 'Keenan',
        memberId: '60d22eff-c820-4d63-9fbd-944bc76f6e22',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4577bbcd-e030-46b8-869d-ce08e8c4677f',
        postedDateTime: 1570917932084,
        comment: 'Eres el mejor Dybala●',
        nickname: 'Alejandro Hirales',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Alejandro',
        surname: 'Hirales',
        memberId: '28c1aef9-858c-4f2c-9fde-11727d998206',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '90eaa3c2-389c-4ad7-a9a5-e0aa0ab78719',
        postedDateTime: 1570237621468,
        comment: "I am your fan, I would like to meet u some day... But I'm in Brazil now.\n",
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1570236355/avatar_070da272-9353-4d98-a13c-90b8231144bf.jpg',
        nickname: 'Vinícius Melo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Vinícius',
        surname: 'Melo',
        memberId: '070da272-9353-4d98-a13c-90b8231144bf',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'b748cfca-7b6f-4eb4-bbbb-50557eb26484',
        postedDateTime: 1570067098407,
        comment:
          'Le pedi una tuya a Anto en su momento, ya que nunca se pudo dar y ahora esta esta publicación . Te puedo hacer el mangazo? :) Un abrazo.',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1555704527/avatar_be8bb93c-6a44-45e9-b61b-92251744d809.jpg?type=square&width=400',
        nickname: 'German Laso',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'German',
        surname: 'Laso',
        memberId: 'be8bb93c-6a44-45e9-b61b-92251744d809',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
        postedDateTime: 1582663817143,
        comment: 'GG',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
        nickname: 'Bruno Lago',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bruno',
        surname: 'Lago',
        memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
        postedDateTime: 1581919062973,
        comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
        nickname: 'Ricardo  D. ',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Ricardo ',
        surname: 'D. ',
        memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
        postedDateTime: 1581079141092,
        comment: 'Life ❤',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
        postedDateTime: 1581079113209,
        comment: 'Best  player ',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
        postedDateTime: 1581079099376,
        comment: 'Wooow',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
        postedDateTime: 1576734479356,
        comment: 'Genioooollll',
        nickname: 'Bautista Peirano',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bautista',
        surname: 'Peirano',
        memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
        postedDateTime: 1576259890052,
        comment: '❤️❤️❤️❤️',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
        nickname: 'Andrea Ceballos',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Andrea',
        surname: 'Ceballos',
        memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
        postedDateTime: 1576157447699,
        comment: 'Paulo Dybala❤️',
        nickname: 'Shirley Francisca Libombo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Shirley Francisca',
        surname: 'Libombo',
        memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9a1f4b81-37f7-4085-96ab-96d49e698b27',
        postedDateTime: 1574312808356,
        comment: '\uD83D\uDC99',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1574799206/avatar_dde77c00-a3d7-4570-b65d-7eefcf6c0c3a.jpg?type=square&width=400',
        nickname: 'Isabel Jakob',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Isabel',
        surname: 'Jakob',
        memberId: 'dde77c00-a3d7-4570-b65d-7eefcf6c0c3a',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb0cc2e2-e7f4-4e22-b1eb-6d99cc5e77aa',
        postedDateTime: 1573333064364,
        comment: 'Wowwww Pauloooo...\uD83D\uDE0D',
        avatarUrl: 'https://graph.facebook.com/10221096707835667/picture',
        nickname: 'Astryd Colella',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Astryd',
        surname: 'Colella',
        memberId: '61ae0de4-94ea-4ad7-a6a4-75c668b04a53',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb74b6f1-7da5-44e4-88bd-67e55539ffe8',
        postedDateTime: 1573322097311,
        comment: 'A',
        avatarUrl: 'https://graph.facebook.com/2171749249821485/picture',
        nickname: 'Tejas Ganesh',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Tejas',
        surname: 'Ganesh',
        memberId: '77a266c7-810f-4268-a122-aede1b04ace7',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cf75ca2d-d3f4-4d2e-8d8b-07008d093e82',
        postedDateTime: 1572965949144,
        comment: "He's a cracker.mans got an arsenal kit... respect",
        nickname: 'Sean Keenan',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Sean',
        surname: 'Keenan',
        memberId: '60d22eff-c820-4d63-9fbd-944bc76f6e22',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4577bbcd-e030-46b8-869d-ce08e8c4677f',
        postedDateTime: 1570917932084,
        comment: 'Eres el mejor Dybala●',
        nickname: 'Alejandro Hirales',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Alejandro',
        surname: 'Hirales',
        memberId: '28c1aef9-858c-4f2c-9fde-11727d998206',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '90eaa3c2-389c-4ad7-a9a5-e0aa0ab78719',
        postedDateTime: 1570237621468,
        comment: "I am your fan, I would like to meet u some day... But I'm in Brazil now.\n",
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1570236355/avatar_070da272-9353-4d98-a13c-90b8231144bf.jpg',
        nickname: 'Vinícius Melo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Vinícius',
        surname: 'Melo',
        memberId: '070da272-9353-4d98-a13c-90b8231144bf',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'b748cfca-7b6f-4eb4-bbbb-50557eb26484',
        postedDateTime: 1570067098407,
        comment:
          'Le pedi una tuya a Anto en su momento, ya que nunca se pudo dar y ahora esta esta publicación . Te puedo hacer el mangazo? :) Un abrazo.',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1555704527/avatar_be8bb93c-6a44-45e9-b61b-92251744d809.jpg?type=square&width=400',
        nickname: 'German Laso',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'German',
        surname: 'Laso',
        memberId: 'be8bb93c-6a44-45e9-b61b-92251744d809',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
        postedDateTime: 1582663817143,
        comment: 'GG',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
        nickname: 'Bruno Lago',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bruno',
        surname: 'Lago',
        memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
        postedDateTime: 1581919062973,
        comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
        nickname: 'Ricardo  D. ',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Ricardo ',
        surname: 'D. ',
        memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
        postedDateTime: 1581079141092,
        comment: 'Life ❤',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
        postedDateTime: 1581079113209,
        comment: 'Best  player ',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
        postedDateTime: 1581079099376,
        comment: 'Wooow',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
        postedDateTime: 1576734479356,
        comment: 'Genioooollll',
        nickname: 'Bautista Peirano',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bautista',
        surname: 'Peirano',
        memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
        postedDateTime: 1576259890052,
        comment: '❤️❤️❤️❤️',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
        nickname: 'Andrea Ceballos',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Andrea',
        surname: 'Ceballos',
        memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
        postedDateTime: 1576157447699,
        comment: 'Paulo Dybala❤️',
        nickname: 'Shirley Francisca Libombo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Shirley Francisca',
        surname: 'Libombo',
        memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9a1f4b81-37f7-4085-96ab-96d49e698b27',
        postedDateTime: 1574312808356,
        comment: '\uD83D\uDC99',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1574799206/avatar_dde77c00-a3d7-4570-b65d-7eefcf6c0c3a.jpg?type=square&width=400',
        nickname: 'Isabel Jakob',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Isabel',
        surname: 'Jakob',
        memberId: 'dde77c00-a3d7-4570-b65d-7eefcf6c0c3a',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb0cc2e2-e7f4-4e22-b1eb-6d99cc5e77aa',
        postedDateTime: 1573333064364,
        comment: 'Wowwww Pauloooo...\uD83D\uDE0D',
        avatarUrl: 'https://graph.facebook.com/10221096707835667/picture',
        nickname: 'Astryd Colella',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Astryd',
        surname: 'Colella',
        memberId: '61ae0de4-94ea-4ad7-a6a4-75c668b04a53',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb74b6f1-7da5-44e4-88bd-67e55539ffe8',
        postedDateTime: 1573322097311,
        comment: 'A',
        avatarUrl: 'https://graph.facebook.com/2171749249821485/picture',
        nickname: 'Tejas Ganesh',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Tejas',
        surname: 'Ganesh',
        memberId: '77a266c7-810f-4268-a122-aede1b04ace7',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cf75ca2d-d3f4-4d2e-8d8b-07008d093e82',
        postedDateTime: 1572965949144,
        comment: "He's a cracker.mans got an arsenal kit... respect",
        nickname: 'Sean Keenan',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Sean',
        surname: 'Keenan',
        memberId: '60d22eff-c820-4d63-9fbd-944bc76f6e22',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4577bbcd-e030-46b8-869d-ce08e8c4677f',
        postedDateTime: 1570917932084,
        comment: 'Eres el mejor Dybala●',
        nickname: 'Alejandro Hirales',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Alejandro',
        surname: 'Hirales',
        memberId: '28c1aef9-858c-4f2c-9fde-11727d998206',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '90eaa3c2-389c-4ad7-a9a5-e0aa0ab78719',
        postedDateTime: 1570237621468,
        comment: "I am your fan, I would like to meet u some day... But I'm in Brazil now.\n",
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1570236355/avatar_070da272-9353-4d98-a13c-90b8231144bf.jpg',
        nickname: 'Vinícius Melo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Vinícius',
        surname: 'Melo',
        memberId: '070da272-9353-4d98-a13c-90b8231144bf',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'b748cfca-7b6f-4eb4-bbbb-50557eb26484',
        postedDateTime: 1570067098407,
        comment:
          'Le pedi una tuya a Anto en su momento, ya que nunca se pudo dar y ahora esta esta publicación . Te puedo hacer el mangazo? :) Un abrazo.',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1555704527/avatar_be8bb93c-6a44-45e9-b61b-92251744d809.jpg?type=square&width=400',
        nickname: 'German Laso',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'German',
        surname: 'Laso',
        memberId: 'be8bb93c-6a44-45e9-b61b-92251744d809',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
        postedDateTime: 1582663817143,
        comment: 'GG',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
        nickname: 'Bruno Lago',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bruno',
        surname: 'Lago',
        memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
        postedDateTime: 1581919062973,
        comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
        nickname: 'Ricardo  D. ',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Ricardo ',
        surname: 'D. ',
        memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
        postedDateTime: 1581079141092,
        comment: 'Life ❤',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
        postedDateTime: 1581079113209,
        comment: 'Best  player ',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
        postedDateTime: 1581079099376,
        comment: 'Wooow',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
        postedDateTime: 1576734479356,
        comment: 'Genioooollll',
        nickname: 'Bautista Peirano',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bautista',
        surname: 'Peirano',
        memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
        postedDateTime: 1576259890052,
        comment: '❤️❤️❤️❤️',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
        nickname: 'Andrea Ceballos',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Andrea',
        surname: 'Ceballos',
        memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
        postedDateTime: 1576157447699,
        comment: 'Paulo Dybala❤️',
        nickname: 'Shirley Francisca Libombo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Shirley Francisca',
        surname: 'Libombo',
        memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9a1f4b81-37f7-4085-96ab-96d49e698b27',
        postedDateTime: 1574312808356,
        comment: '\uD83D\uDC99',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1574799206/avatar_dde77c00-a3d7-4570-b65d-7eefcf6c0c3a.jpg?type=square&width=400',
        nickname: 'Isabel Jakob',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Isabel',
        surname: 'Jakob',
        memberId: 'dde77c00-a3d7-4570-b65d-7eefcf6c0c3a',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb0cc2e2-e7f4-4e22-b1eb-6d99cc5e77aa',
        postedDateTime: 1573333064364,
        comment: 'Wowwww Pauloooo...\uD83D\uDE0D',
        avatarUrl: 'https://graph.facebook.com/10221096707835667/picture',
        nickname: 'Astryd Colella',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Astryd',
        surname: 'Colella',
        memberId: '61ae0de4-94ea-4ad7-a6a4-75c668b04a53',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb74b6f1-7da5-44e4-88bd-67e55539ffe8',
        postedDateTime: 1573322097311,
        comment: 'A',
        avatarUrl: 'https://graph.facebook.com/2171749249821485/picture',
        nickname: 'Tejas Ganesh',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Tejas',
        surname: 'Ganesh',
        memberId: '77a266c7-810f-4268-a122-aede1b04ace7',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cf75ca2d-d3f4-4d2e-8d8b-07008d093e82',
        postedDateTime: 1572965949144,
        comment: "He's a cracker.mans got an arsenal kit... respect",
        nickname: 'Sean Keenan',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Sean',
        surname: 'Keenan',
        memberId: '60d22eff-c820-4d63-9fbd-944bc76f6e22',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4577bbcd-e030-46b8-869d-ce08e8c4677f',
        postedDateTime: 1570917932084,
        comment: 'Eres el mejor Dybala●',
        nickname: 'Alejandro Hirales',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Alejandro',
        surname: 'Hirales',
        memberId: '28c1aef9-858c-4f2c-9fde-11727d998206',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '90eaa3c2-389c-4ad7-a9a5-e0aa0ab78719',
        postedDateTime: 1570237621468,
        comment: "I am your fan, I would like to meet u some day... But I'm in Brazil now.\n",
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1570236355/avatar_070da272-9353-4d98-a13c-90b8231144bf.jpg',
        nickname: 'Vinícius Melo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Vinícius',
        surname: 'Melo',
        memberId: '070da272-9353-4d98-a13c-90b8231144bf',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'b748cfca-7b6f-4eb4-bbbb-50557eb26484',
        postedDateTime: 1570067098407,
        comment:
          'Le pedi una tuya a Anto en su momento, ya que nunca se pudo dar y ahora esta esta publicación . Te puedo hacer el mangazo? :) Un abrazo.',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1555704527/avatar_be8bb93c-6a44-45e9-b61b-92251744d809.jpg?type=square&width=400',
        nickname: 'German Laso',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'German',
        surname: 'Laso',
        memberId: 'be8bb93c-6a44-45e9-b61b-92251744d809',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c79ea7de-94b6-4603-b60a-6e7379498b31',
        postedDateTime: 1582663817143,
        comment: 'GG',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1582574163/avatar_81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2.jpg',
        nickname: 'Bruno Lago',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bruno',
        surname: 'Lago',
        memberId: '81a05ba1-ca2a-4bb9-b378-2e6ecde9bdb2',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'ba747679-13f9-4328-85cc-d6c54787f768',
        postedDateTime: 1581919062973,
        comment: 'Aloha Pablo!\nUn cordobe en Hawaii, saluda nero:)',
        nickname: 'Ricardo  D. ',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Ricardo ',
        surname: 'D. ',
        memberId: 'b814cf9c-3163-4119-b607-cebd1be97f66',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9bf52549-92e5-4c80-8a57-6b4c7a7fb1b5',
        postedDateTime: 1581079141092,
        comment: 'Life ❤',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '25796eed-46de-4356-9212-d850bd9bcb0b',
        postedDateTime: 1581079113209,
        comment: 'Best  player ',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '8bf0ce17-cb2d-4695-9278-5d618b422ec3',
        postedDateTime: 1581079099376,
        comment: 'Wooow',
        nickname: 'Mohammad Banaderi',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Mohammad',
        surname: 'Banaderi',
        memberId: '0e8995e4-af3b-4c5a-b064-7d4d1c1f3cd3',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '62685dd0-4193-4501-991c-543c9ae52b3d',
        postedDateTime: 1576734479356,
        comment: 'Genioooollll',
        nickname: 'Bautista Peirano',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Bautista',
        surname: 'Peirano',
        memberId: '5aef5453-af88-45d2-b56b-220100682e7f',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'c16eeab4-5cd5-4205-b74e-bacf5017d5d7',
        postedDateTime: 1576259890052,
        comment: '❤️❤️❤️❤️',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1552634134/avatar_56a4cbce-5f13-49c8-9476-025102e4f222.jpg',
        nickname: 'Andrea Ceballos',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Andrea',
        surname: 'Ceballos',
        memberId: '56a4cbce-5f13-49c8-9476-025102e4f222',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4a95dc92-e54e-49c5-83ab-9f4d5c698ad4',
        postedDateTime: 1576157447699,
        comment: 'Paulo Dybala❤️',
        nickname: 'Shirley Francisca Libombo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Shirley Francisca',
        surname: 'Libombo',
        memberId: '9fa725aa-90ae-467f-93bc-e0e14884a097',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '9a1f4b81-37f7-4085-96ab-96d49e698b27',
        postedDateTime: 1574312808356,
        comment: '\uD83D\uDC99',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1574799206/avatar_dde77c00-a3d7-4570-b65d-7eefcf6c0c3a.jpg?type=square&width=400',
        nickname: 'Isabel Jakob',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Isabel',
        surname: 'Jakob',
        memberId: 'dde77c00-a3d7-4570-b65d-7eefcf6c0c3a',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb0cc2e2-e7f4-4e22-b1eb-6d99cc5e77aa',
        postedDateTime: 1573333064364,
        comment: 'Wowwww Pauloooo...\uD83D\uDE0D',
        avatarUrl: 'https://graph.facebook.com/10221096707835667/picture',
        nickname: 'Astryd Colella',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Astryd',
        surname: 'Colella',
        memberId: '61ae0de4-94ea-4ad7-a6a4-75c668b04a53',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cb74b6f1-7da5-44e4-88bd-67e55539ffe8',
        postedDateTime: 1573322097311,
        comment: 'A',
        avatarUrl: 'https://graph.facebook.com/2171749249821485/picture',
        nickname: 'Tejas Ganesh',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Tejas',
        surname: 'Ganesh',
        memberId: '77a266c7-810f-4268-a122-aede1b04ace7',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'cf75ca2d-d3f4-4d2e-8d8b-07008d093e82',
        postedDateTime: 1572965949144,
        comment: "He's a cracker.mans got an arsenal kit... respect",
        nickname: 'Sean Keenan',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Sean',
        surname: 'Keenan',
        memberId: '60d22eff-c820-4d63-9fbd-944bc76f6e22',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '4577bbcd-e030-46b8-869d-ce08e8c4677f',
        postedDateTime: 1570917932084,
        comment: 'Eres el mejor Dybala●',
        nickname: 'Alejandro Hirales',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Alejandro',
        surname: 'Hirales',
        memberId: '28c1aef9-858c-4f2c-9fde-11727d998206',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: '90eaa3c2-389c-4ad7-a9a5-e0aa0ab78719',
        postedDateTime: 1570237621468,
        comment: "I am your fan, I would like to meet u some day... But I'm in Brazil now.\n",
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1570236355/avatar_070da272-9353-4d98-a13c-90b8231144bf.jpg',
        nickname: 'Vinícius Melo',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'Vinícius',
        surname: 'Melo',
        memberId: '070da272-9353-4d98-a13c-90b8231144bf',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
      {
        externalId: 'b748cfca-7b6f-4eb4-bbbb-50557eb26484',
        postedDateTime: 1570067098407,
        comment:
          'Le pedi una tuya a Anto en su momento, ya que nunca se pudo dar y ahora esta esta publicación . Te puedo hacer el mangazo? :) Un abrazo.',
        avatarUrl:
          'https://avatar.otro.com/image/upload/v1555704527/avatar_be8bb93c-6a44-45e9-b61b-92251744d809.jpg?type=square&width=400',
        nickname: 'German Laso',
        star: false,
        vip: false,
        expandable: false,
        numberOfReplies: 0,
        numberOfLikes: 0,
        userReplies: [],
        importantReplies: [],
        reported: false,
        reportCleared: false,
        owner: false,
        likedByMe: false,
        forename: 'German',
        surname: 'Laso',
        memberId: 'be8bb93c-6a44-45e9-b61b-92251744d809',
        removed: false,
        blocked: false,
        hidden: false,
        expandAfter: false,
        reply: false,
      },
    ],
  };
};

const mapDispatchToProps = dispatch => ({
  pageInteraction: action => dispatch(commentsPageInteraction(action)),
});

export default compose(
  connect(
    mapStateToProps,
    mapDispatchToProps
  )
  // withRequest({
  //   pageable: true,
  // })
)(CommentBlock);
