export default {
  HERO: 'HERO',
  PORTRAITLIST: 'PORTRAITLIST',
  SECTIONLIST: 'SECTIONLIST',
  CAROUSELSECTION: 'CAROUSELSECTION',
  EXPANDINGCAROUSELSECTION: 'EXPANDINGCAROUSELSECTION',
  GALLERY: 'GALLERY',
  SIGNPOST: 'SIGNED_POST',
  CONTENT_INDEX_HEADER: 'CONTENT_INDEX_HEADER',
};
